### ISSUE TITLE
User Story 4 : Creation of profile page, back-end for sign up/login/job posting

### ISSUE THREAD

**Issue by radeefchowdhury** [SSathu/Magma-soen341project2023#44]
# Tasks
- [ ] Create a profile page with all of the users information. 
- [ ] Functional sign up back-end
- [ ] Functional log in back-end
- [ ] Functional job posting back-end
